from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_account, name='register'),
    path('register/admin/', views.register_account, name='admin_register'),
    path('upload/', views.upload_document, name='upload'),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dismiss-notification/', views.dismiss_notification, name='dismiss_notification'),
    path('organization-overview/', views.organization_overview, name='organization_overview'),
    path('organization-overview/logo/', views.update_organization_logo, name='update_organization_logo'),
    path('organization-overview/rename/', views.rename_organization, name='rename_organization'),
    path('organization-overview/officers/add/', views.add_organization_officer, name='add_organization_officer'),
    path('organization-overview/officers/<int:officer_id>/delete/', views.delete_organization_officer, name='delete_organization_officer'),
    path('organization-overview/officers/<int:officer_id>/update/', views.update_organization_officer, name='update_organization_officer'),
    path('organization-overview/officers/<int:officer_id>/photo/', views.update_organization_officer_photo, name='update_organization_officer_photo'),
    path('organization-overview/officers/<int:officer_id>/<str:direction>/', views.move_organization_officer, name='move_organization_officer'),
    path('documents/<int:document_id>/delete/', views.delete_document, name='delete_document'),
    path('folders/<int:folder_id>/delete/', views.delete_folder, name='delete_folder'),
    path('folders/<int:folder_id>/cancel/', views.cancel_folder_submission, name='cancel_folder_submission'),
    path('documents/<int:document_id>/cancel/', views.cancel_document_submission, name='cancel_document_submission'),
    path('folders/<int:folder_id>/forward/', views.organization_forward_folder, name='organization_forward_folder'),
    path('documents/<int:document_id>/checklist/', views.update_correction_checklist, name='update_correction_checklist'),
    path('signed-copies/upload/', views.upload_signed_copy, name='upload_signed_copy'),
    path('account/delete/', views.delete_account, name='delete_account'),
    path('adviser-dashboard/', views.adviser_dashboard, name='adviser_dashboard'),
    path('adviser-dashboard/documents/<int:document_id>/edit/', views.adviser_edit_document, name='adviser_edit_document'),
    path('adviser-dashboard/documents/<int:document_id>/forward/', views.adviser_forward_document, name='adviser_forward_document'),
    path('adviser-dashboard/folders/<int:folder_id>/forward/', views.adviser_forward_folder, name='adviser_forward_folder'),
    path('adviser-dashboard/folders/<int:folder_id>/cancel/', views.adviser_cancel_folder_submission, name='adviser_cancel_folder_submission'),
    path('adviser-dashboard/documents/<int:document_id>/cancel/', views.adviser_cancel_document_submission, name='adviser_cancel_document_submission'),
    path('adviser-dashboard/documents/<int:document_id>/view/', views.adviser_view_document, name='adviser_view_document'),
    path('adviser-dashboard/documents/<int:document_id>/download/', views.adviser_download_document, name='adviser_download_document'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/organizations/', views.admin_organizations_list, name='admin_organizations_list'),
    path('admin-dashboard/organizations/<int:organization_id>/', views.admin_organization_overview, name='admin_organization_overview'),
    path('admin-dashboard/documents/<int:document_id>/edit/', views.admin_edit_document, name='admin_edit_document'),
    path('admin-dashboard/documents/<int:document_id>/forward-rank1/', views.rank2_forward_document, name='rank2_forward_document'),
    path('admin-dashboard/folders/<int:folder_id>/forward-rank1/', views.rank2_forward_folder, name='rank2_forward_folder'),
    path('admin-dashboard/documents/<int:document_id>/view/', views.admin_view_document, name='admin_view_document'),
    path('admin-dashboard/documents/<int:document_id>/download/', views.admin_download_document, name='admin_download_document'),
    path('documents/<int:document_id>/corrections/add/', views.add_correction_item, name='add_correction_item'),
    path('corrections/<int:correction_id>/edit/', views.edit_correction_item, name='edit_correction_item'),
    path('corrections/<int:correction_id>/resolve/', views.resolve_correction_item, name='resolve_correction_item'),
    path('corrections/<int:correction_id>/delete/', views.delete_correction_item, name='delete_correction_item'),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/clear-all/', views.clear_all_notifications, name='clear_all_notifications'),
    # Binary file serving endpoints
    path('files/organization/<int:organization_id>/logo/', views.serve_organization_logo, name='serve_organization_logo'),
    path('files/officer/<int:officer_id>/photo/', views.serve_officer_photo, name='serve_officer_photo'),
    path('files/template/<int:template_id>/', views.serve_template_file, name='serve_template_file'),
    path('files/signed-copy/<int:signed_copy_id>/', views.serve_signed_copy, name='serve_signed_copy'),
    path('files/document/<int:document_id>/', views.serve_uploaded_file, name='serve_uploaded_file'),
]
