# Generated by Django 6.0.4 on 2026-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_editable_file_add_correction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='correction_checklist_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
