# Generated by Django 6.0.4 on 2026-05-11 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_correction_checklist_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='adviser_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adviser_reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='adviser_status',
            field=models.CharField(choices=[('PENDING', 'Pending Adviser Review'), ('CORRECTED', 'Corrected'), ('APPROVED', 'Approved by Adviser')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='adviser_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='forwarded_to_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='section',
            field=models.CharField(choices=[('EXPLANATORY_REPORTS', 'Explanatory Report(s)'), ('REACCREDITATION', 'Reaccreditation'), ('ACCREDITATION', 'Accreditation'), ('ORGANIZATION_EVENTS', 'Organization Events')], default='EXPLANATORY_REPORTS', max_length=40),
        ),
        migrations.CreateModel(
            name='AdviserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisers', to='documents.organizationprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileSectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('EXPLANATORY_REPORTS', 'Explanatory Report(s)'), ('REACCREDITATION', 'Reaccreditation'), ('ACCREDITATION', 'Accreditation'), ('ORGANIZATION_EVENTS', 'Organization Events')], max_length=40, unique=True)),
                ('template_file', models.FileField(upload_to='templates/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section'],
            },
        ),
    ]
