# Generated by Django 6.0.4 on 2026-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_adviser_reviewed_by_document_adviser_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='section',
            field=models.CharField(choices=[('EXPLANATORY_REPORTS', 'Explanatory Report'), ('REACCREDITATION', 'Reaccreditation'), ('ACCREDITATION', 'Accreditation'), ('ORGANIZATION_EVENTS', 'Organization Events')], default='EXPLANATORY_REPORTS', max_length=40),
        ),
        migrations.AlterField(
            model_name='filesectiontemplate',
            name='section',
            field=models.CharField(choices=[('EXPLANATORY_REPORTS', 'Explanatory Report'), ('REACCREDITATION', 'Reaccreditation'), ('ACCREDITATION', 'Accreditation'), ('ORGANIZATION_EVENTS', 'Organization Events')], max_length=40, unique=True),
        ),
    ]
