# Generated by Codex on 2026-05-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('photo', models.FileField(blank=True, null=True, upload_to='officers/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='documents.organizationprofile')),
            ],
            options={
                'ordering': ['display_order', 'created_at', 'id'],
            },
        ),
    ]
