# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_organizationofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='admin_notification_seen_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='organizationofficer',
            name='photo_updated_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
