# Generated by Django 6.0.4 on 2026-06-11 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SECTION_MAP = {
    'EXPLANATORY_REPORTS': 'ACCOMPLISHMENT_REPORT',
    'ORGANIZATION_EVENTS': 'ORGANIZATION_ACTIVITIES',
    'ACCREDITATION_REACCREDITATION': 'REACCREDITATION_ACCREDITATION',
    'ACCREDITATION': 'REACCREDITATION_ACCREDITATION',
    'REACCREDITATION': 'REACCREDITATION_ACCREDITATION',
}

SECTION_LABELS = {
    'ORGANIZATION_ACTIVITIES': 'Organization Activities',
    'REACCREDITATION_ACCREDITATION': 'Reaccreditation and Accreditation',
    'ACCOMPLISHMENT_REPORT': 'Accomplishment Report',
}


def migrate_sections_and_seed_folders(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    FileSectionTemplate = apps.get_model('documents', 'FileSectionTemplate')
    SubmissionFolder = apps.get_model('documents', 'SubmissionFolder')

    for old_section, new_section in SECTION_MAP.items():
        Document.objects.filter(section=old_section).update(section=new_section)

    for new_section in set(SECTION_MAP.values()):
        old_sections = [
            old_section
            for old_section, mapped_section in SECTION_MAP.items()
            if mapped_section == new_section
        ]
        existing_template = FileSectionTemplate.objects.filter(section=new_section).first()
        legacy_templates = FileSectionTemplate.objects.filter(section__in=old_sections).order_by('id')

        if existing_template:
            legacy_templates.exclude(pk=existing_template.pk).delete()
        else:
            template = legacy_templates.first()
            if template:
                template.section = new_section
                template.save(update_fields=['section'])
                legacy_templates.exclude(pk=template.pk).delete()

    for document in Document.objects.filter(folder__isnull=True).order_by('uploaded_at', 'id'):
        folder = SubmissionFolder.objects.create(
            user_id=document.user_id,
            section=document.section,
            name=document.title or SECTION_LABELS.get(document.section, 'Submission Folder'),
            forwarded_to_admin_at=document.forwarded_to_admin_at,
            admin_notification_seen_at=document.admin_notification_seen_at,
            rank2_reviewed_by_id=document.rank2_reviewed_by_id,
            forwarded_to_rank1_at=document.forwarded_to_rank1_at,
            rank1_notification_seen_at=document.rank1_notification_seen_at,
        )
        document.folder = folder
        document.save(update_fields=['folder'])


def restore_legacy_sections(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    FileSectionTemplate = apps.get_model('documents', 'FileSectionTemplate')

    Document.objects.filter(section='ORGANIZATION_ACTIVITIES').update(section='ORGANIZATION_EVENTS')
    Document.objects.filter(section='REACCREDITATION_ACCREDITATION').update(
        section='ACCREDITATION_REACCREDITATION'
    )
    Document.objects.filter(section='ACCOMPLISHMENT_REPORT').update(section='EXPLANATORY_REPORTS')
    FileSectionTemplate.objects.filter(section='ORGANIZATION_ACTIVITIES').update(
        section='ORGANIZATION_EVENTS'
    )
    FileSectionTemplate.objects.filter(section='REACCREDITATION_ACCREDITATION').update(
        section='ACCREDITATION_REACCREDITATION'
    )
    FileSectionTemplate.objects.filter(section='ACCOMPLISHMENT_REPORT').update(
        section='EXPLANATORY_REPORTS'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_document_correction_reviewed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='rank',
            field=models.CharField(choices=[('RANK_1', 'Director of Student Affairs and Services (DSAS)'), ('RANK_2', 'Campus Organization In-charge (COI)')], default='RANK_1', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='section',
            field=models.CharField(choices=[('ORGANIZATION_ACTIVITIES', 'Organization Activities'), ('REACCREDITATION_ACCREDITATION', 'Reaccreditation and Accreditation'), ('ACCOMPLISHMENT_REPORT', 'Accomplishment Report')], default='ORGANIZATION_ACTIVITIES', max_length=40),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CORRECTED', 'Corrected'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED_BY_COI', 'Approved by COI'), ('READY_FOR_PRINTING', 'Ready for Printing')], default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='filesectiontemplate',
            name='section',
            field=models.CharField(choices=[('ORGANIZATION_ACTIVITIES', 'Organization Activities'), ('REACCREDITATION_ACCREDITATION', 'Reaccreditation and Accreditation'), ('ACCOMPLISHMENT_REPORT', 'Accomplishment Report')], max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='SubmissionFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ORGANIZATION_ACTIVITIES', 'Organization Activities'), ('REACCREDITATION_ACCREDITATION', 'Reaccreditation and Accreditation'), ('ACCOMPLISHMENT_REPORT', 'Accomplishment Report')], max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_to_admin_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notification_seen_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to_rank1_at', models.DateTimeField(blank=True, null=True)),
                ('rank1_notification_seen_at', models.DateTimeField(blank=True, null=True)),
                ('rank2_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank2_reviewed_folders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SignedScannedCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('signed_file', models.FileField(upload_to='signed_copies/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_to_adviser_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to_coi_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to_dsas_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_copies', to='documents.submissionfolder')),
            ],
            options={
                'ordering': ['-uploaded_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.submissionfolder'),
        ),
        migrations.RunPython(migrate_sections_and_seed_folders, restore_legacy_sections),
    ]
