# Generated by Django 6.0.4 on 2026-06-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_adminprofile_rank_alter_document_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesectiontemplate',
            options={'ordering': ['section', '-uploaded_at', 'id']},
        ),
        migrations.AlterField(
            model_name='filesectiontemplate',
            name='section',
            field=models.CharField(choices=[('ORGANIZATION_ACTIVITIES', 'Organization Activities'), ('REACCREDITATION_ACCREDITATION', 'Reaccreditation and Accreditation'), ('ACCOMPLISHMENT_REPORT', 'Accomplishment Report')], max_length=40),
        ),
    ]
