# Generated by Django 6.0.4 on 2026-07-13 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_filecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('FILE_FORWARDED', 'File Forwarded'), ('FILE_SUBMITTED', 'File Submitted'), ('FILE_APPROVED', 'File Approved'), ('FILE_CORRECTED', 'File Corrected'), ('SIGNED_COPY_UPLOADED', 'Signed Copy Uploaded'), ('SIGNED_COPY_FORWARDED', 'Signed Copy Forwarded')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.document')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('signed_copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.signedscannedcopy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
