# Generated by Django 6.0.4 on 2026-07-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('TEXT_CORRECTION', 'Text Correction'), ('FILE_ADDITION', 'File Addition'), ('SECTION_CORRECTION', 'Section Correction'), ('GENERAL_CORRECTION', 'General Correction')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('page_number', models.IntegerField(blank=True, help_text='Page number for text corrections', null=True)),
                ('section', models.CharField(blank=True, help_text='Document section', max_length=100, null=True)),
                ('current_text', models.TextField(blank=True, help_text='Current text that needs to be changed')),
                ('suggested_text', models.TextField(blank=True, help_text='Suggested replacement text')),
                ('description', models.TextField(help_text='Detailed description of the correction needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the correction was resolved')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_corrections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_corrections', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_items', to='documents.document')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_items', to='documents.submissionfolder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'status', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='FileComment',
        ),
    ]
