# Generated by Django 6.0.4 on 2026-07-20 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_correctionitem_delete_filecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='corrected_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='filesectiontemplate',
            name='template_file',
        ),
        migrations.RemoveField(
            model_name='organizationofficer',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='signedscannedcopy',
            name='signed_file',
        ),
        migrations.AddField(
            model_name='document',
            name='corrected_file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='corrected_file_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='corrected_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='corrected_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='corrected_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='corrected_file_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='corrected_file_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_corrected_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_file_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesectiontemplate',
            name='template_file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='filesectiontemplate',
            name='template_file_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filesectiontemplate',
            name='template_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesectiontemplate',
            name='template_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filesectiontemplate',
            name='template_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationofficer',
            name='photo_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organizationofficer',
            name='photo_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationofficer',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationofficer',
            name='photo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationofficer',
            name='photo_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationofficer',
            name='photo_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationofficer',
            name='photo_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_officer_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_logos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signedscannedcopy',
            name='signed_file_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='signedscannedcopy',
            name='signed_file_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signedscannedcopy',
            name='signed_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signedscannedcopy',
            name='signed_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signedscannedcopy',
            name='signed_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
